### ISSUE TITLE
Installing a module 'ng4-loading-spinner' getting error : ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file)

### ISSUE THREAD

**Issue by vishnusbabu** [Hacklone/angular2-cool-storage#11]
After installing a new module 'ng4-loading-spinner'
 I am getting a error
`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /var/www/html/buddy-admin/node_modules/ng4-loading-spinner/node_modules/@angular/core/core.d.ts, resolving symbol Ng4LoadingSpinnerModule in /var/www/html/buddy-admin/node_modules/ng4-loading-spinner/ng4LoadingSpinner.module.d.ts, resolving symbol Ng4LoadingSpinnerModule in /var/www/html/buddy-admin/node_modules/ng4-loading-spinner/ng4LoadingSpinner.module.d.ts
`

**Comment by Hacklone** [comment]
Seems like that there’s a problem with ng4-loading-spinner. Probably it wasn’t built to use with AOT.
I think this issue is not related to angular2-cool-storage 🙂
