### ISSUE TITLE
How to share data across subdomains?

### ISSUE THREAD

**Issue by afsar-infobeans** [Hacklone/angular2-cool-storage#12]
Hi,

I want the localstorage data from mydomain.com to subdomain.mydomain.com?

If there is only a iframe and postmessage solution then i dont want.Also i believe that using cookie it is possible so why to use this plugin?

Please suggest

**Comment by Hacklone** [comment]
Hey, you could set the document.domain to my domain.com as local storage is always bound to the documents domain, so cool-local-storage won’t be able to do this magic, sorry
