### ISSUE TITLE
Got Issue with module 'AppModule' and and cool-storage-base.d.ts

### ISSUE THREAD

**Issue by Bosper** [Hacklone/angular2-cool-storage#2]
Hello, like mate before me, I have same Issue with 
`Unexpected value 'CoolStorageModule' imported by the module 'AppModule',`

and also compiler was yelled for: 
readonly length: number;

in cool-storage-base.d.ts.

Repaired by adding: 
readonly(length: number);

But `Unexpected value 'CoolStorageModule' imported by the module 'AppModule',`  still exist. Newest version doesn't resolved problem.

**Comment by kashban** [comment]
Check https://github.com/Hacklone/angular2-cool-storage/issues/1 for the reason on this.

Only the library developer(s) can fix this by adding a metadata file for the Ionic 2 AOT compiler.

**Comment by kashban** [comment]
Any news about this?

**Comment by Hacklone** [comment]
Hey,

Currently ngc doesn't support TS 2.1.1 which is required for this project, so upvote: https://github.com/angular/angular/issues/12966

Thanks :)

**Comment by kashban** [comment]
Thanks for looking into this. Done.

**Comment by Hacklone** [comment]
Is this issue still active with the 1.2.0 release?

**Comment by Hacklone** [comment]
This is fixed in version 1.2.0
