### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported.

### ISSUE THREAD

**Issue by Octopixell** [Hacklone/angular2-cool-storage#6]
After updating angular-cli (now on version `1.0.0-rc.0`) I'm getting the following error and I'm not sure how to get this fixed. Maybe you can help?

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 
resolving symbol NgModule in /Users/marco/TaxiID/corporate.taxiid.nl/node_modules/angular2-cool-storage/node_modules/@angular/core/src/metadata/ng_module.d.ts, 
resolving symbol NgModule in /Users/marco/TaxiID/corporate.taxiid.nl/node_modules/angular2-cool-storage/node_modules/@angular/core/src/metadata.d.ts, 
resolving symbol NgModule in /Users/marco/TaxiID/corporate.taxiid.nl/node_modules/angular2-cool-storage/node_modules/@angular/core/src/core.d.ts, 
resolving symbol NgModule in /Users/marco/TaxiID/corporate.taxiid.nl/node_modules/angular2-cool-storage/node_modules/@angular/core/index.d.ts, 
resolving symbol CoolStorageModule in /Users/marco/TaxiID/corporate.taxiid.nl/node_modules/angular2-cool-storage/index.d.ts, 
resolving symbol CoolStorageModule in /Users/marco/TaxiID/corporate.taxiid.nl/node_modules/angular2-cool-storage/index.d.ts
```

Thanks for making such an awesome module!

**Comment by Hacklone** [comment]
Hey,

This should be fixed in the latest version.

Please remove the ```node_modules/angular2-cool-storage``` folder.
Then install the latest version of angular2-cool-storage.

Hope this helps :)

**Comment by Octopixell** [comment]
Hi Hacklone,

Thanks for the super quick reply! Instead of removing the `node_modules` directory and just running `npm i` I've now ran `npm uninstall --save angular2-cool-storage` followed by `npm install --save angular2-cool-storage` and that fixed it.

Happy it was as simple as that hah! Thanks for your help!

**Comment by pablozandona** [comment]
Same problem here with angular/core: 4.3.0-beta.0

`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /node_modules/angular2-cool-storage/node_modules/@angular/core/core.d.ts, resolving symbol CoolStorageModule in node_modules/angular2-cool-storage/index.d.ts, resolving symbol CoolStorageModule in node_modules/angular2-cool-storage/index.d.ts`

**Comment by anvial** [comment]
It seems, we need to reopen issue

**Comment by amitgaur208** [comment]
Yes i am getting same issue in latest version
"angular2-cool-storage": "^3.1.0",
