### ISSUE TITLE
rror encountered resolving symbol values statically

### ISSUE THREAD

**Issue by EdwinJDiaz** [Hacklone/angular2-cool-storage#8]
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /node_modules/angular2-cool-storage/node_modules/@angular/core/core.d.ts, resolving symbol CoolStorageModule in node_modules/angular2-cool-storage/index.d.ts, resolving symbol CoolStorageModule in node_modules/angular2-cool-storage/index.d.t

![image](https://user-images.githubusercontent.com/11430535/29134438-3a2f378e-7cfc-11e7-893c-b2a514278aa1.png)

**Comment by Hacklone** [comment]
Hey,

I'm also using this with AOT and it works well for me.
What specific version of angular and ngc are you using?

Thanks, 
Barna

**Comment by anvial** [comment]
Did you find any solution of this problem?

**Comment by Hacklone** [comment]
Can somebody reproduce this? Maybe a plunker or something?

**Comment by lwpassvoice** [comment]
That happened to me, and there is my dependencies:
`"dependencies": {
    "@angular/animations": "^4.3.4",
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/common": "^4.3.4",
    "@angular/compiler": "^4.3.4",
    "@angular/core": "^4.3.4",
    "@angular/forms": "^4.3.4",
    "@angular/http": "^4.3.4",
    "@angular/material": "^2.0.0-beta.11",
    "@angular/platform-browser": "^4.3.4",
    "@angular/platform-browser-dynamic": "^4.3.4",
    "@angular/router": "^4.3.4",
    "@greg-md/ng-lazy-load": "^1.0.4",
    "@swimlane/ngx-datatable": "^7.1.1",
    "angular-progress-http": "^0.4.0",
    "angular2-cool-storage": "^3.1.0",
    "angular2-echarts": "^1.1.4",
    "angular2-moment": "^1.3.3",
    "core-js": "^2.4.1",
    "cryptojs": "^2.5.3",
    "echarts": "^3.5.1",
    "file-saver": "^1.3.3",
    "moment": "^2.18.1",
    "ng2-image-lazy-load": "^2.0.9",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "^4.3.4",
    "@types/jasmine": "2.5.53",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
`

**Comment by amitgaur208** [comment]
I am getting same issue with latest version

 "angular2-cool-storage": "^3.1.0",

**Comment by amitgaur208** [comment]
@lwpassvoice  Same situation https://github.com/MikaAK/angular-safeguard/issues/29
:D
